version: 1
formatters:
  basic:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: basic
    filename: chessmaster-process.log
    maxBytes: 10240
    backupCount: 3
loggers:
  handler:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handler: [console, file]