spring:
  application:
    name: chessmaster-web
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  thymeleaf:
    enabled: true
    mode: HTML
    prefix: classpath:/static/
    suffix: .html
    cache: false
    check-template: true
    encoding: UTF-8

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
